development:
  adapter: sqlserver
  mode: dblib
  dataserver: local
  database: clogs_development
  username: dummy
  password: dummy
  timeout: 5000

test:
  adapter: sqlserver
  mode: dblib
  dataserver: local
  database: clogs_test
  username: dummy
  password: dummy
  timeout: 5000

production:
  adapter: sqlserver
  mode: dblib
  dataserver: local
  database: clogs
  username: dummy
  password: dummy
  timeout: 5000

